### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by Jesse-Kerr** [guillermo-navas-palencia/optbinning#185]
After installing `optbinning` on macOS Monterrey, version 12.4, with python 3.9, I get this error when trying to import `optbinning`:

```
from optbinning import OptimalBinning
Backend MacOSX is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/jessekerr/Documents/Apple/HDI_ICC/venv/lib/python3.9/site-packages/optbinning/__init__.py", line 2, in <module>
    from .binning import BinningProcess
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/jessekerr/Documents/Apple/HDI_ICC/venv/lib/python3.9/site-packages/optbinning/binning/__init__.py", line 1, in <module>
    from .binning import OptimalBinning
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/jessekerr/Documents/Apple/HDI_ICC/venv/lib/python3.9/site-packages/optbinning/binning/binning.py", line 26, in <module>
    from .cp import BinningCP
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/jessekerr/Documents/Apple/HDI_ICC/venv/lib/python3.9/site-packages/optbinning/binning/cp.py", line 11, in <module>
    from ortools.sat.python import cp_model
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/jessekerr/Documents/Apple/HDI_ICC/venv/lib/python3.9/site-packages/ortools/sat/python/cp_model.py", line 55, in <module>
    from ortools.sat.python import swig_helper
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/jessekerr/Documents/Apple/HDI_ICC/venv/lib/python3.9/site-packages/ortools/sat/python/swig_helper.so, 0x0002): tried: '/Users/jessekerr/Documents/Apple/HDI_ICC/venv/lib/python3.9/site-packages/ortools/sat/python/swig_helper.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h'))
```

**Comment by guillermo-navas-palencia** [comment]
Hi @Jesse-Kerr,

I am not a macOS user, but it seems to me that this is a Google-OR-Tools-related problem. Could you try to install other versions of or-tools and see if this error persists?  The error seems quite specific:

ImportError: dlopen(/Users/jessekerr/Documents/Apple/HDI_ICC/venv/lib/python3.9/site-packages/ortools/sat/python/swig_helper.so, 0x0002): tried: '/Users/jessekerr/Documents/Apple/HDI_ICC/venv/lib/python3.9/site-packages/ortools/sat/python/swig_helper.so' (mach-o file, but is **an incompatible architecture (have 'arm64', need 'x86_64h')**)
