### ISSUE TITLE
optbinning.binning module not found

### ISSUE THREAD

**Issue by SuryaThiru** [guillermo-navas-palencia/optbinning#7]
Imports fail and throws a `ModuleNotFoundError`
```python
from optbinning import OptimalBinning
```
**Traceback:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/surya/miniconda3/envs/ml/lib/python3.7/site-packages/optbinning/__init__.py", line 1, in <module>
    from .binning.binning import OptimalBinning
ModuleNotFoundError: No module named 'optbinning.binning'
```

**Comment by guillermo-navas-palencia** [comment]
Hi, 

Sorry, there was an error on the last build uploaded to pip. Please download an install from source the last release. I will fix it shortly.

**Comment by guillermo-navas-palencia** [comment]
Thanks for noticing. Version 0.3.1 fixes the problem.

**Comment by SuryaThiru** [comment]
Updating fixed the issue. Thank you
